name: Reboisasi

on:

  push:
    branches:
      - main
      
  schedule:
  - cron: "1 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3     
        with:
         persist-credentials: false
         fetch-depth: 1

      - name: Modify last update
        run: |
          cat > README.md
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > README.md
          
      - name: Commit changes
        run: |
          git config --local user.email "belajarqywok@gmail.com"
          git config --local user.name "belajarqywok"
          git add -A
          git commit -m "Penanaman Pohon"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.TOKEN }}
